#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime spotify github \
					instagram claude youtube gmail weather apps logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--ff" || "$1" == "--ag" ]]; then
	close_dash && /usr/bin/antigravity &

elif [[ "$1" == "--tg" || "$1" == "--br" ]]; then
	close_dash && brave &

elif [[ "$1" == "--dc" || "$1" == "--vs" ]]; then
	close_dash && code &

elif [[ "$1" == "--tr" ]]; then
	close_dash && kitty &

elif [[ "$1" == "--fm" ]]; then
	close_dash && dolphin &

elif [[ "$1" == "--ge" || "$1" == "--sp" ]]; then
	close_dash && spotify &

elif [[ "$1" == "--cd" || "$1" == "--wa" ]]; then
	# wa is whatsapp, cd was dolphin originally. Let's support both.
	if [[ "$1" == "--wa" ]]; then
		close_dash && whatsapp-for-linux &
	else
		close_dash && dolphin &
	fi

elif [[ "$1" == "--gp" || "$1" == "--oo" ]]; then
	if [[ "$1" == "--oo" ]]; then
		close_dash && /snap/bin/onlyoffice-desktopeditors &
	else
		close_dash && kitty nvim &
	fi

elif [[ "$1" == "--vb" || "$1" == "--vl" ]]; then
	close_dash && vlc &

fi
