#!/bin/bash

## Open links in firefox
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`
cmd="brave"

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime spotify github \
					instagram claude youtube gmail weather apps logout sleep reboot poweroff folders 
	rm -rf "$FILE"
}

if [[ "$1" == "--mail" ]]; then
	close_dash && ${cmd} "https://mail.google.com/mail/u/1/#inbox"

elif [[ "$1" == "--gh" ]]; then
	close_dash && ${cmd} "https://github.com"

elif [[ "$1" == "--in" ]]; then
	close_dash && ${cmd} "https://www.instagram.com"

elif [[ "$1" == "--cl" ]]; then
	close_dash && ${cmd} "https://claude.ai"

elif [[ "$1" == "--yt" ]]; then
	close_dash && ${cmd} "https://youtube.com"

fi
