# Core Colors
background            #101510
foreground            #e0e4db
selection_foreground  #9cd49f
selection_background  #013913
cursor                #9cd49f
cursor_text_color     #101510

# Regular Colors
color0  #101510
color1  #ffb4ab
color2  #9cd49f
color3  #a1ced6
color4  #b8f1b9
color5  #d4e8d1
color6  #b8ccb5
color7  #e0e4db

# Bright Colors
color8  #363a35
color9  #ffb4ab
color10 #9cd49f
color11 #a1ced6
color12 #b8f1b9
color13 #d4e8d1 
color14 #b8ccb5
color15 #e0e4db
