# Core Colors
background            #14140c
foreground            #e7e2d5
selection_foreground  #d0ca73
selection_background  #343200
cursor                #d0ca73
cursor_text_color     #14140c

# Regular Colors
color0  #14140c
color1  #ffb4ab
color2  #d0ca73
color3  #a5d0ba
color4  #ede68c
color5  #e9e4be
color6  #ccc8a3
color7  #e7e2d5

# Bright Colors
color8  #3b3930
color9  #ffb4ab
color10 #d0ca73
color11 #a5d0ba
color12 #ede68c
color13 #e9e4be 
color14 #ccc8a3
color15 #e7e2d5
